### ISSUE TITLE
restful-timeseries-webapp-3.3.0-rc.3-SNAPSHOT.war results in HTTP 404 under Tomcat 8

### ISSUE THREAD

**Issue by meliezer** [52North/SensorWebClient#149]
Hello,
The webapp creates a cache, the logs are fine, but the user sees HTTP 404.
The war file of sensorwebclient-webapp is fine.

With kind regards,
Menashè

**Comment by ridoo** [comment]
@meliezer with the information you provide (almost nothing) it is impossible to reproduce this error.

If this error does not appear to happen anymore, you should close the ticket.

**Comment by meliezer** [comment]
Actually there was no error. Sorry. Closing.
