### ISSUE TITLE
Header links are not active upon starting the web application

### ISSUE THREAD

**Issue by meliezer** [52North/SensorWebClient#151]
Header links are not active upon starting the web application. Clicking has no effect as long as the "Search timeseries" window is open. I've discovered by chance how to click there... It's not documented, neither the Permalink option, which actually should be disabled once it's not relevant (e.g., the main window).

With kind regards,
Menashè

**Comment by ridoo** [comment]
I don't know what you mean, to be honest ... the header links are clickable unless you have opened the map window to select timeseries (which is a modal window!).

**Comment by meliezer** [comment]
The map window is already open upon starting the web application. The use which may wants to click on Help cannot do it as long as the map window is open. You can call it a "known limitation", but maybe you can show these links only once they can be clicked for not confusing the user.

**Comment by ridoo** [comment]
well, we already had long discussions on the user workflow. we agreed to open the map window so make clear that this is the entry point ... we did not recognize, that the header links are not clickable at that moment. 

However, probably this is not a big issue, as the modal window greys out everything else around (a quite common widget btw).
